"""
DO NOT MODIFY THIS FILE.  It is automatically generated by Stinger-IPC 0.6.15 and changes will be over-written
on the next generation.

It contains enumerations used by the Simple interface.

LICENSE: This generated code is not subject to any license restrictions from the generator itself.
TODO: Get license text from stinger file
"""

from pydantic import BaseModel, Field, PlainValidator, PlainSerializer, ConfigDict
from datetime import datetime, timedelta, timezone

UTC = timezone.utc

from typing import Optional, Union, List
import base64
from enum import IntEnum
import sys

# Use typing_extensions for Python < 3.9 compatibility
if sys.version_info >= (3, 9):
    from typing import Annotated
else:
    from typing_extensions import Annotated


def base64_decode_if_str(value: Union[str, bytes, None]) -> Optional[bytes]:
    """If the value is a string, decode it from base64 to bytes.  Otherwise return the bytes as-is."""
    if isinstance(value, str):
        return base64.b64decode(value)
    return value


class InterfaceInfo(BaseModel):
    interface_name: str = Field(default="Simple")
    title: str = Field(default="Simple Example Interface")
    version: str = Field(default="0.0.1")
    instance: str
    connection_topic: str
    timestamp: str


class Gender(IntEnum):
    """Interface enum `gender`.
    _No description exists for this enumeration._
    """

    MALE = 1
    FEMALE = 2
    OTHER = 3


class Person(BaseModel):
    """Interface struct `person`."""

    model_config = ConfigDict(populate_by_name=True, strict=True, extra="forbid")
    name: Annotated[
        str,
        Field(
            description="The name of the person",
        ),
    ]
    gender: Annotated[
        Gender,
        Field(
            description="The gender of the person.",
        ),
    ]


class PersonEnteredSignalPayload(BaseModel):
    """Interface signal `person_entered`."""

    model_config = ConfigDict(populate_by_name=True, strict=True, extra="forbid")
    person: Annotated[Person, Field()]


class SchoolProperty(BaseModel):
    """Interface property `school` (multi-value struct)."""

    model_config = ConfigDict(populate_by_name=True, strict=True, extra="forbid")
    name: Annotated[
        str,
        Field(
            description="The name of the school where the person studies.",
        ),
    ]


class TradeNumbersMethodRequest(BaseModel):
    """Interface method `trade_numbers` request object.

    A simple method which trades favorite numbers.
    """

    model_config = ConfigDict(populate_by_name=True, strict=True, extra="forbid")
    your_number: Annotated[
        int,
        Field(
            description="Your favorite number.",
        ),
    ]


class TradeNumbersMethodResponse(BaseModel):
    """Interface method `trade_numbers` response object.

    A simple method which trades favorite numbers.
    """

    model_config = ConfigDict(populate_by_name=True, strict=True, extra="forbid")
    my_number: Annotated[
        int,
        Field(
            description="My favorite number",
        ),
    ]
