image: gitpod/workspace-full

vscode:
  extensions:
    - ms-python.python
    - redhat.vscode-yaml
    - webfreak.debug

tasks:
  - name: Install dependencies
    before: |
      sudo apt update -y && sudo apt install -y mosquitto mosquitto-clients libboost-dev libboost-thread-dev libmosquitto-dev rapidjson-dev
      gp sync-done aptinstall
      uv sync
      npm install -g npm@8.10.0
      npm install -g @asyncapi/generator
    init:
      bin/generate_everything.sh
    command: |
      mosquitto
      gp sync-done brokerrun
    openMode: tab-after
  - name: MQTT Subscribe
    command: |
      gp sync-await brokerrun
      mosquitto_sub -t '#' -v
    openMode: split-right
