# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  THREADS: '{{default "16" .THREADS}}'
  INTERFACES: [full, simple, testable, signal_only]

tasks:
  default:
    desc: Generate and compile all interfaces
    deps:
      - task: python:generate-all
      - task: cpp:compile-all
      - task: rust:check-all
      - task: markdown:generate-all
      - task: web:generate-all
      - task: protobuf:generate-all

  python:generate:*:
    desc: Generate Python code for an interface
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/python/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/python/**
    cmds:
      - mkdir -p ./example_interfaces/{{.IFACE}}/output/python/
      - uv run stinger generate {{.CLI_ARGS}} --language python ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/python/
      - uv run black ./example_interfaces/{{.IFACE}}/output/python/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python-alternate:generate:*:
    desc: Generate Python code for an interface with alternative settings
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/python/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output-alternate/python/**
    cmds:
      - mkdir -p ./example_interfaces/{{.IFACE}}/output-alternate/python/
      - uv run stinger generate {{.CLI_ARGS}} --language python --config example_interfaces/alternate.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output-alternate/python/
      - uv run black ./example_interfaces/{{.IFACE}}/output-alternate/python/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python:generate-all:
    desc: Generate Python code for all interfaces
    deps:
      - for: [full, simple, testable, signal_only]
        task: python:generate:{{ .ITEM }}
      - for: [full, simple, testable, signal_only]
        task: python-alternate:generate:{{ .ITEM }}

  cpp:generate:*:
    desc: Generate C++ code for an interface
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/cpp/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/cpp/**
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language cpp ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/cpp/
      - clang-format --style=file:clang-format-config.yaml ./example_interfaces/{{.IFACE}}/output/cpp/include/*.hpp ./example_interfaces/{{.IFACE}}/output/cpp/src/*.cpp ./example_interfaces/{{.IFACE}}/output/cpp/examples/*.cpp -i
    vars:
      IFACE: '{{index .MATCH 0}}'

  cpp:compile:*:
    desc: Compile C++ code for an interface
    deps:
      - task: cpp:generate:{{index .MATCH 0}}
    sources:
      - example_interfaces/{{.IFACE}}/output/cpp/**
    cmds:
      - mkdir -p ./example_interfaces/{{.IFACE}}/output/cpp/build
      - cd ./example_interfaces/{{.IFACE}}/output/cpp/build && cmake .. && make -j {{.THREADS}}
    vars:
      IFACE: '{{index .MATCH 0}}'

  cpp:compile-all:
    desc: Compile C++ code for all interfaces
    deps:
      - for: [full, simple, testable, signal_only]
        task: cpp:compile:{{ .ITEM }}
  
  rust:generate:*:
    desc: Generate Rust code for an interface
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/rust/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/rust/**
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language rust ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/rust/
      - cd ./example_interfaces/{{.IFACE}}/output/rust/ && cargo fmt
    vars:
      IFACE: '{{index .MATCH 0}}'

  rust:check:*:
    desc: Check Rust code for an interface
    dir: example_interfaces/{{.IFACE}}/output/rust/
    deps:
      - task: rust:generate:{{index .MATCH 0}}
    sources:
      - ./**
    cmds:
      - cargo check --all-features
      - cargo check --example {{.IFACE}}_client_demo --features client
      - cargo check --example {{.IFACE}}_server_demo --features server
    vars:
      IFACE: '{{index .MATCH 0}}'

  rust:check-all:
    desc: Check Rust code for all interfaces
    deps:
      - for: [full, simple, testable, signal_only]
        task: rust:check:{{ .ITEM }}

  markdown:generate:*:
    desc: Generate markdown documentation for an interface
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/markdown/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/markdown/*
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language markdown ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/markdown/
    vars:
      IFACE: '{{index .MATCH 0}}'
  
  markdown:generate-all:
    desc: Generate markdown documentation for all interfaces
    deps:
      - for: [full, simple, testable, signal_only]
        task: markdown:generate:{{ .ITEM }}

  web:generate:*:
    desc: Generate web documentation for an interface
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/web/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/web/**
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language web ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/web/
    vars:
      IFACE: '{{index .MATCH 0}}'
  
  web:generate-all:
    desc: Generate web documentation for all interfaces
    deps:
      - for: [full, simple, testable, signal_only]
        task: web:generate:{{ .ITEM }}
  
  protobuf:generate:*:
    desc: Generate Protobuf code for an interface
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/protobuf/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/protobuf/**
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language protobuf ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/protobuf/
    vars:
      IFACE: '{{index .MATCH 0}}'

  protobuf:generate-all:
    desc: Generate Protobuf code for all interfaces
    deps:
      - for: [full, simple, testable, signal_only]
        task: protobuf:generate:{{ .ITEM }}
  
  clean:
    desc: Clean all generated files
    cmds:
      - rm -rf ./example_interfaces/*/output/*