# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  THREADS: '{{default "16" .THREADS}}'
  INTERFACES: [full, simple, testable, signal_only, weather]

tasks:
  default:
    desc: Generate and compile all interfaces
    deps:
      - task: python:generate
      - task: python:unittest
      - task: cpp:compile
      - task: rust:check
      - task: markdown:generate
      - task: web:generate
      - task: protobuf:check

  validate:*:
    desc: Validate a specific interface schema
    sources:
      - schemas/schema.yaml
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    cmds:
      - uv run stinger validate ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    vars:
      IFACE: '{{index .MATCH 0}}'

  validate:
    desc: Validate all interface schemas
    deps:
      - for: { var: INTERFACES }
        task: validate:{{ .ITEM }}
    
  python:generate:*:
    desc: Generate Python code for an interface
    deps:
      - task: validate:{{index .MATCH 0}}
    sources:
      - pyproject.toml
      - stingeripc/**/*.py
      - stingeripc/templates/python/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/python/**
    cmds:
      - mkdir -p ./example_interfaces/{{.IFACE}}/output/python/
      - uv run stinger generate {{.CLI_ARGS}} --language python --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/python/
      - uv run black ./example_interfaces/{{.IFACE}}/output/python/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python37:generate:*:
    desc: Generate Python 3.7 code for an interface with alternative settings
    deps:
      - task: validate:{{index .MATCH 0}}
    sources:
      - pyproject.toml
      - stingeripc/*.py
      - stingeripc/tools/*.py
      - stingeripc/templates/python/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/python37/**
    cmds:
      - mkdir -p ./example_interfaces/{{.IFACE}}/output/python37/
      - uv run stinger generate {{.CLI_ARGS}} --language python --config ./example_interfaces/python37.toml --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/python37/
      - uv run black ./example_interfaces/{{.IFACE}}/output/python37/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python-alt1:generate:*:
    desc: Generate Python code for an interface with alternative settings
    deps:
      - task: validate:{{index .MATCH 0}}
    sources:
      - pyproject.toml
      - stingeripc/*.py
      - stingeripc/tools/*.py
      - stingeripc/templates/python/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/python-alt1/**
    cmds:
      - mkdir -p ./example_interfaces/{{.IFACE}}/output/python-alt1/
      - uv run stinger generate {{.CLI_ARGS}} --language python --config ./example_interfaces/app-owned-props.toml --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/python-alt1/
      - uv run black ./example_interfaces/{{.IFACE}}/output/python-alt1/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python:generate:
    desc: Generate Python code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: python:generate:{{ .ITEM }}
      - for: { var: INTERFACES }
        task: python37:generate:{{ .ITEM }}
      - for: { var: INTERFACES }
        task: python-alt1:generate:{{ .ITEM }}

  python:unittest:*:
    desc: Run Python unit tests for an interface
    dir: example_interfaces/{{.IFACE}}/output/python/
    deps:
      - task: python:generate:{{index .MATCH 0}}
    sources:
      - example_interfaces/{{.IFACE}}/output/python/tests/**
      - example_interfaces/{{.IFACE}}/output/python/src/**
    cmds:
      - uv run pytest -vv
    vars:
      IFACE: '{{index .MATCH 0}}'

  python-alt1:unittest:*:
    desc: Run Python unit tests for an interface generated with alternative settings
    dir: example_interfaces/{{.IFACE}}/output/python-alt1/
    deps:
      - task: python-alt1:generate:{{index .MATCH 0}}
    sources:
      - example_interfaces/{{.IFACE}}/output/python-alt1/tests/*.py
      - example_interfaces/{{.IFACE}}/output/python-alt1/src/*.py
    cmds:
      - uv run pytest -vv
    vars:
      IFACE: '{{index .MATCH 0}}'

  python:unittest:
    desc: Run Python unit tests for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: python:unittest:{{ .ITEM }}
      - for: { var: INTERFACES }
        task: python-alt1:unittest:{{ .ITEM }}

  python:mypy:*:
    desc: Run mypy type checking for an interface
    dir: example_interfaces/{{.IFACE}}/output/python/
    deps:
      - task: python:generate:{{index .MATCH 0}}
    sources:
      - ./src/**
      - ./tests/**
    cmds:
      - uv run mypy ./src/ ./tests/
    vars:
      IFACE: '{{index .MATCH 0}}'
    
  python-alt1:mypy:*:
    desc: Run mypy type checking for an interface generated with alternative settings
    dir: example_interfaces/{{.IFACE}}/output/python-alt1/
    deps:
      - task: python-alt1:generate:{{index .MATCH 0}}
    sources:
      - ./src/**
      - ./tests/**
    cmds:
      - uv run mypy ./src/ ./tests/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python:mypy:
    desc: Run mypy type checking for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: python:mypy:{{ .ITEM }}
      - for: { var: INTERFACES }
        task: python-alt1:mypy:{{ .ITEM }}

  python:
    desc: Run all python releated tasks
    deps:
      - task: python:generate
      - task: python:unittest
      - task: python:mypy

  cpp:generate:*:
    desc: Generate C++ code for an interface
    sources:
      - pyproject.toml
      - stingeripc/*.py
      - stingeripc/tools/*
      - stingeripc/tests/*
      - stingeripc/templates/cpp/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/cpp/**
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language cpp --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/cpp/
      - clang-format --style=file:clang-format-config.yaml ./example_interfaces/{{.IFACE}}/output/cpp/include/*.hpp ./example_interfaces/{{.IFACE}}/output/cpp/src/*.cpp ./example_interfaces/{{.IFACE}}/output/cpp/examples/*.cpp -i
    vars:
      IFACE: '{{index .MATCH 0}}'

  cpp:generate:
    desc: Generate C++ code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: cpp:generate:{{ .ITEM }}

  cpp:compile:*:
    desc: Compile C++ code for an interface
    deps:
      - task: cpp:generate:{{index .MATCH 0}}
    sources:
      - example_interfaces/{{.IFACE}}/output/cpp/**
    cmds:
      - mkdir -p ./example_interfaces/{{.IFACE}}/output/cpp/build
      - cd ./example_interfaces/{{.IFACE}}/output/cpp/build && cmake .. && make -j {{.THREADS}}
    vars:
      IFACE: '{{index .MATCH 0}}'

  cpp:compile:
    desc: Compile C++ code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: cpp:compile:{{ .ITEM }}
  
  rust:generate:*:
    desc: Generate Rust code for an interface
    sources:
      - pyproject.toml
      - stingeripc/*.py
      - stingeripc/templates/rust/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/rust/**
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language rust --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/rust/
      - cd ./example_interfaces/{{.IFACE}}/output/rust/ && cargo fmt
    vars:
      IFACE: '{{index .MATCH 0}}'

  rust:generate:
    desc: Generate Rust code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: rust:generate:{{ .ITEM }}

  rust:check:*:
    desc: Check Rust code for an interface
    dir: example_interfaces/{{.IFACE}}/output/rust/
    deps:
      - task: rust:generate:{{index .MATCH 0}}
    sources:
      - ./**
    cmds:
      - cargo check --all-features
      - cargo check --example {{.IFACE}}_client_demo --features client
      - cargo check --example {{.IFACE}}_server_demo --features server
    vars:
      IFACE: '{{index .MATCH 0}}'

  rust:check:
    desc: Check Rust code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: rust:check:{{ .ITEM }}

  markdown:generate:*:
    desc: Generate markdown documentation for an interface
    sources:
      - stingeripc/*.py
      - stingeripc/templates/markdown/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/markdown/*
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language markdown --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/markdown/
    vars:
      IFACE: '{{index .MATCH 0}}'
  
  markdown:generate:
    desc: Generate markdown documentation for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: markdown:generate:{{ .ITEM }}

  web:generate:*:
    desc: Generate web documentation for an interface
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/web/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/web/**
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language web --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/web/
    vars:
      IFACE: '{{index .MATCH 0}}'
  
  web:generate:
    desc: Generate web documentation for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: web:generate:{{ .ITEM }}
  
  protobuf:generate:*:
    desc: Generate Protobuf code for an interface
    deps:
      - task: validate:{{index .MATCH 0}}
    sources:
      - stingeripc/*/*.py
      - stingeripc/tools/*
      - stingeripc/symbols/protobuf.py
      - stingeripc/templates/protobuf/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - example_interfaces/{{.IFACE}}/output/protobuf/**
    cmds:
      - mkdir -p ./example_interfaces/{{.IFACE}}/output/protobuf/
      - uv run stinger generate {{.CLI_ARGS}} --language protobuf ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml example_interfaces/{{.IFACE}}/output/protobuf/
    vars:
      IFACE: '{{index .MATCH 0}}'

  protobuf:generate:
    desc: Generate Protobuf code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: protobuf:generate:{{ .ITEM }}
  
  protobuf:check:*:
    desc: Check Protobuf code for an interface
    deps:
      - task: protobuf:generate:{{index .MATCH 0}}
    sources:
      - example_interfaces/{{.IFACE}}/output/protobuf/**
    cmds:
      - protoc --proto_path=./example_interfaces/{{.IFACE}}/output/protobuf/ --descriptor_set_out=/dev/null ./example_interfaces/{{.IFACE}}/output/protobuf/*.proto
    vars:
      IFACE: '{{index .MATCH 0}}'

  protobuf:check:
    desc: Check Protobuf code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: protobuf:check:{{ .ITEM }}

  clean:
    desc: Clean all generated files
    cmds:
      - rm -rf ./example_interfaces/*/output/*