# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  THREADS: '{{default "16" .THREADS}}'
  INTERFACES: [full, simple, testable, signal_only, weather]
  GENERATED_DIR: '{{default "./generated" .GENERATED_DIR}}'

tasks:
  default:
    desc: Generate and compile all interfaces
    deps:
      - task: python:generate
      - task: python:unittest
      - task: cpp:compile
      - task: rust:unittest
      - task: markdown:generate
      - task: web:generate
      - task: protobuf:check

  validate:*:
    desc: Validate a specific interface schema
    sources:
      - schemas/schema.yaml
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    cmds:
      - uv run stinger validate ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    vars:
      IFACE: '{{index .MATCH 0}}'

  validate:
    desc: Validate all interface schemas
    deps:
      - for: { var: INTERFACES }
        task: validate:{{ .ITEM }}
    
  python:generate:*:
    desc: Generate Python code for an interface
    deps:
      - task: validate:{{index .MATCH 0}}
    sources:
      - pyproject.toml
      - stingeripc/**/*.py
      - stingeripc/templates/python/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/python/**"
    cmds:
      - mkdir -p {{.GENERATED_DIR}}/{{.IFACE}}/python/
      - uv run stinger generate {{.CLI_ARGS}} --language python --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml {{.GENERATED_DIR}}/{{.IFACE}}/python/
      - uv run black --target-version py312 {{.GENERATED_DIR}}/{{.IFACE}}/python/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python37:generate:*:
    desc: Generate Python 3.7 code for an interface with alternative settings
    deps:
      - task: validate:{{index .MATCH 0}}
    sources:
      - pyproject.toml
      - stingeripc/*.py
      - stingeripc/tools/*.py
      - stingeripc/templates/python/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/python37/**"
    cmds:
      - mkdir -p {{.GENERATED_DIR}}/{{.IFACE}}/python37/
      - uv run stinger generate {{.CLI_ARGS}} --language python --config ./example_interfaces/python37.toml --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml {{.GENERATED_DIR}}/{{.IFACE}}/python37/
      - uv run black --target-version py37 {{.GENERATED_DIR}}/{{.IFACE}}/python37/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python-alt1:generate:*:
    desc: Generate Python code for an interface with alternative settings
    deps:
      - task: validate:{{index .MATCH 0}}
    sources:
      - pyproject.toml
      - stingeripc/*.py
      - stingeripc/tools/*.py
      - stingeripc/templates/python/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/python-alt1/**"
    cmds:
      - mkdir -p {{.GENERATED_DIR}}/{{.IFACE}}/python-alt1/
      - uv run stinger generate {{.CLI_ARGS}} --language python --config ./example_interfaces/app-owned-props.toml --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml {{.GENERATED_DIR}}/{{.IFACE}}/python-alt1/
      - uv run black --target-version py312 {{.GENERATED_DIR}}/{{.IFACE}}/python-alt1/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python:generate:
    desc: Generate Python code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: python:generate:{{ .ITEM }}
      - for: { var: INTERFACES }
        task: python37:generate:{{ .ITEM }}
      - for: { var: INTERFACES }
        task: python-alt1:generate:{{ .ITEM }}

  python:unittest:*:
    desc: Run Python unit tests for an interface
    dir: generated/{{.IFACE}}/python/
    deps:
      - task: python:generate:{{index .MATCH 0}}
    sources:
      - example_interfaces/{{.IFACE}}/python/tests/**
      - example_interfaces/{{.IFACE}}/python/src/**
    cmds:
      - uv run pytest -vv
    vars:
      IFACE: '{{index .MATCH 0}}'

  python-alt1:unittest:*:
    desc: Run Python unit tests for an interface {{.GENERATED_DIR}} with alternative settings
    dir: generated/{{.IFACE}}/python-alt1/
    deps:
      - task: python-alt1:generate:{{index .MATCH 0}}
    sources:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/python-alt1/tests/*.py"
      - "{{.GENERATED_DIR}}/{{.IFACE}}/python-alt1/src/*.py"
    cmds:
      - uv run pytest -vv
    vars:
      IFACE: '{{index .MATCH 0}}'

  python:unittest:
    desc: Run Python unit tests for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: python:unittest:{{ .ITEM }}
      - for: { var: INTERFACES }
        task: python-alt1:unittest:{{ .ITEM }}

  python:mypy:*:
    desc: Run mypy type checking for an interface
    dir: generated/{{.IFACE}}/python/
    deps:
      - task: python:generate:{{index .MATCH 0}}
    sources:
      - ./src/**
      - ./tests/**
    cmds:
      - uv run mypy ./src/ ./tests/
    vars:
      IFACE: '{{index .MATCH 0}}'
    
  python-alt1:mypy:*:
    desc: Run mypy type checking for an interface generated with alternative settings
    dir: generated/{{.IFACE}}/python-alt1/
    deps:
      - task: python-alt1:generate:{{index .MATCH 0}}
    sources:
      - ./src/**
      - ./tests/**
    cmds:
      - uv run mypy ./src/ ./tests/
    vars:
      IFACE: '{{index .MATCH 0}}'

  python:mypy:
    desc: Run mypy type checking for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: python:mypy:{{ .ITEM }}
      - for: { var: INTERFACES }
        task: python-alt1:mypy:{{ .ITEM }}

  python:
    desc: Run all python releated tasks
    deps:
      - task: python:generate
      - task: python:unittest
      - task: python:mypy

  cpp:generate:*:
    desc: Generate C++ code for an interface
    sources:
      - pyproject.toml
      - stingeripc/*.py
      - stingeripc/tools/*
      - stingeripc/tests/*
      - stingeripc/templates/cpp/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
      - clang-format-config.yaml
    generates:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/cpp/examples/**"
      - "{{.GENERATED_DIR}}/{{.IFACE}}/cpp/include/**"
      - "{{.GENERATED_DIR}}/{{.IFACE}}/cpp/src/**"
      - "{{.GENERATED_DIR}}/{{.IFACE}}/cpp/cmake/**"
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language cpp --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml "{{.GENERATED_DIR}}/{{.IFACE}}/cpp/"
      - clang-format --style=file:clang-format-config.yaml {{.GENERATED_DIR}}/{{.IFACE}}/cpp/include/*.hpp {{.GENERATED_DIR}}/{{.IFACE}}/cpp/src/*.cpp {{.GENERATED_DIR}}/{{.IFACE}}/cpp/examples/*.cpp -i
    vars:
      IFACE: '{{index .MATCH 0}}'

  cpp:generate:
    desc: Generate C++ code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: cpp:generate:{{ .ITEM }}

  cpp:compile:*:
    desc: Compile C++ code for an interface
    deps:
      - task: cpp:generate:{{index .MATCH 0}}
    sources:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/cpp/**"
    cmds:
      - mkdir -p "{{.GENERATED_DIR}}/{{.IFACE}}/cpp/build"
      - cd "{{.GENERATED_DIR}}/{{.IFACE}}/cpp/build" && cmake .. && make -j {{.THREADS}}
    vars:
      IFACE: '{{index .MATCH 0}}'

  cpp:compile:
    desc: Compile C++ code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: cpp:compile:{{ .ITEM }}
  
  rust:generate:*:
    desc: Generate Rust code for an interface
    sources:
      - pyproject.toml
      - stingeripc/*.py
      - stingeripc/templates/rust/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/rust/**"
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language rust --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml "{{.GENERATED_DIR}}/{{.IFACE}}/rust/"
      - cd "{{.GENERATED_DIR}}/{{.IFACE}}/rust/" && cargo fmt
    vars:
      IFACE: '{{index .MATCH 0}}'

  rust:generate:
    desc: Generate Rust code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: rust:generate:{{ .ITEM }}

  rust:check:*:
    desc: Check Rust code for an interface
    dir: "{{.GENERATED_DIR}}/{{.IFACE}}/rust/"
    deps:
      - task: rust:generate:{{index .MATCH 0}}
    sources:
      - ./**
    cmds:
      - cargo check --all-features
      - cargo check --example {{.IFACE}}_client_demo --features client
      - cargo check --example {{.IFACE}}_server_demo --features server
    vars:
      IFACE: '{{index .MATCH 0}}'

  rust:check:
    desc: Check Rust code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: rust:check:{{ .ITEM }}

  rust:unittest:*:
    desc: Run Rust unit tests for an interface
    dir: "{{.GENERATED_DIR}}/{{.IFACE}}/rust/"
    deps:
      - task: rust:generate:{{index .MATCH 0}}
    sources:
      - ./**
    cmds:
      - cargo test --all-features
    vars:
      IFACE: '{{index .MATCH 0}}'

  rust:unittest:
    desc: Run Rust unit tests for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: rust:unittest:{{ .ITEM }}

  markdown:generate:*:
    desc: Generate markdown documentation for an interface
    sources:
      - stingeripc/*.py
      - stingeripc/templates/markdown/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/markdown/*"
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language markdown --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml "{{.GENERATED_DIR}}/{{.IFACE}}/markdown/"
    vars:
      IFACE: '{{index .MATCH 0}}'
  
  markdown:generate:
    desc: Generate markdown documentation for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: markdown:generate:{{ .ITEM }}

  web:generate:*:
    desc: Generate web documentation for an interface
    sources:
      - stingeripc/**/*.py
      - stingeripc/templates/web/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/web/**"
    cmds:
      - uv run stinger generate {{.CLI_ARGS}} --language web --config ./example_interfaces/topic_prefix.toml ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml "{{.GENERATED_DIR}}/{{.IFACE}}/web/"
    vars:
      IFACE: '{{index .MATCH 0}}'
  
  web:generate:
    desc: Generate web documentation for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: web:generate:{{ .ITEM }}
  
  protobuf:generate:*:
    desc: Generate Protobuf code for an interface
    deps:
      - task: validate:{{index .MATCH 0}}
    sources:
      - stingeripc/*/*.py
      - stingeripc/tools/*
      - stingeripc/symbols/protobuf.py
      - stingeripc/templates/protobuf/**
      - example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml
    generates:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/protobuf/**"
    cmds:
      - mkdir -p "{{.GENERATED_DIR}}/{{.IFACE}}/protobuf/"
      - uv run stinger generate {{.CLI_ARGS}} --language protobuf ./example_interfaces/{{.IFACE}}/{{.IFACE}}.stinger.yaml "{{.GENERATED_DIR}}/{{.IFACE}}/protobuf/"
    vars:
      IFACE: '{{index .MATCH 0}}'

  protobuf:generate:
    desc: Generate Protobuf code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: protobuf:generate:{{ .ITEM }}
  
  protobuf:check:*:
    desc: Check Protobuf code for an interface
    deps:
      - task: protobuf:generate:{{index .MATCH 0}}
    sources:
      - "{{.GENERATED_DIR}}/{{.IFACE}}/protobuf/**"
    cmds:
      - uvx --from=protoc-wrapper@30.2 protoc --proto_path="{{.GENERATED_DIR}}/{{.IFACE}}/protobuf/" --descriptor_set_out=/dev/null "{{.GENERATED_DIR}}/{{.IFACE}}/protobuf/*.proto"
    vars:
      IFACE: '{{index .MATCH 0}}'

  protobuf:check:
    desc: Check Protobuf code for all interfaces
    deps:
      - for: { var: INTERFACES }
        task: protobuf:check:{{ .ITEM }}

  generate:
    desc: Generate code and documentation for all interfaces
    deps:
      - task: python:generate
      - task: cpp:generate
      - task: rust:generate
      - task: markdown:generate
      - task: web:generate
      - task: protobuf:generate

  clean:
    desc: Clean all generated files
    cmds:
      - rm -rf "{{.GENERATED_DIR}}/*"
