"""
Generated by Stinger-IPC code generator 0.6.21.
"""

from time import sleep
import signal
import os
from typing import Optional, Union, List
from datetime import datetime, timedelta, UTC
from pyqttier import Mqtt5Connection, MqttTransportType, MqttTransport
from fullipc.server import FullServer
from fullipc.property import FullPropertyAccess
from fullipc.interface_types import *


class FullPropertyOwnership:
    def __init__(self):
        self._favorite_number = 42
        self._favorite_foods = FavoriteFoodsProperty(
            drink="apples",
            slices_of_pizza=42,
            breakfast="apples",
        )
        self._lunch_menu = LunchMenuProperty(
            monday=Lunch(drink=True, sandwich="apples", crackers=3.14, day=DayOfTheWeek.SATURDAY, order_number=42, time_of_lunch=datetime.now(UTC), duration_of_lunch=timedelta(seconds=3536)),
            tuesday=Lunch(drink=True, sandwich="apples", crackers=3.14, day=DayOfTheWeek.SATURDAY, order_number=42, time_of_lunch=datetime.now(UTC), duration_of_lunch=timedelta(seconds=3536)),
        )
        self._family_name = "apples"
        self._last_breakfast_time = datetime.now(UTC)
        self._last_birthdays = LastBirthdaysProperty(
            mom=datetime.now(UTC),
            dad=datetime.now(UTC),
            sister=datetime.now(UTC),
            brothers_age=42,
        )

    def get_property_favorite_number(self):
        """Return the value for the 'favorite_number' property."""
        return self._favorite_number

    def set_property_favorite_number(self, value: int):
        """Set the value for the 'favorite_number' property."""
        print(f"~~> Received update for 'favorite_number' property: {value}")
        self._favorite_number = value

    def get_property_favorite_foods(self):
        """Return the value for the 'favorite_foods' property."""
        return self._favorite_foods

    def set_property_favorite_foods(self, value: FavoriteFoodsProperty):
        """Set the value for the 'favorite_foods' property."""
        print(f"~~> Received update for 'favorite_foods' property: {value}")
        self._favorite_foods = value

    def get_property_lunch_menu(self):
        """Return the value for the 'lunch_menu' property."""
        return self._lunch_menu

    def get_property_family_name(self):
        """Return the value for the 'family_name' property."""
        return self._family_name

    def set_property_family_name(self, value: str):
        """Set the value for the 'family_name' property."""
        print(f"~~> Received update for 'family_name' property: {value}")
        self._family_name = value

    def get_property_last_breakfast_time(self):
        """Return the value for the 'last_breakfast_time' property."""
        return self._last_breakfast_time

    def set_property_last_breakfast_time(self, value: datetime):
        """Set the value for the 'last_breakfast_time' property."""
        print(f"~~> Received update for 'last_breakfast_time' property: {value}")
        self._last_breakfast_time = value

    def get_property_last_birthdays(self):
        """Return the value for the 'last_birthdays' property."""
        return self._last_birthdays

    def set_property_last_birthdays(self, value: LastBirthdaysProperty):
        """Set the value for the 'last_birthdays' property."""
        print(f"~~> Received update for 'last_birthdays' property: {value}")
        self._last_birthdays = value


if __name__ == "__main__":
    """
    This shows an example on how to run the code.  Ideally, your app should do something similar, but use the methods in
    a more meaningful way.
    """

    property_owner = FullPropertyOwnership()
    property_access = FullPropertyAccess(
        favorite_number_getter=property_owner.get_property_favorite_number,
        favorite_number_setter=property_owner.set_property_favorite_number,
        favorite_foods_getter=property_owner.get_property_favorite_foods,
        favorite_foods_setter=property_owner.set_property_favorite_foods,
        lunch_menu_getter=property_owner.get_property_lunch_menu,
        family_name_getter=property_owner.get_property_family_name,
        family_name_setter=property_owner.set_property_family_name,
        last_breakfast_time_getter=property_owner.get_property_last_breakfast_time,
        last_breakfast_time_setter=property_owner.set_property_last_breakfast_time,
        last_birthdays_getter=property_owner.get_property_last_birthdays,
        last_birthdays_setter=property_owner.set_property_last_birthdays,
    )

    transport = MqttTransport(MqttTransportType.TCP, "localhost", 1883)
    conn = Mqtt5Connection(transport, client_id=os.environ.get("CLIENT_ID", "py-server-demo"))
    server = FullServer(conn, os.environ.get("SERVICE_ID", "py-server-demo:1"), property_access)

    @server.handle_add_numbers
    def add_numbers(first: int, second: int, third: Optional[int]) -> int:
        """This is an example handler for the 'addNumbers' method."""
        print(f"--> Running add_numbers({first}, {second}, {third})'")
        return 42

    @server.handle_do_something
    def do_something(task_to_do: str) -> DoSomethingMethodResponse:
        """This is an example handler for the 'doSomething' method."""
        print(f"--> Running do_something({task_to_do})'")
        return DoSomethingMethodResponse(label="apples", identifier=42)

    @server.handle_what_time_is_it
    def what_time_is_it() -> datetime:
        """This is an example handler for the 'what_time_is_it' method."""
        print(f"--> Running what_time_is_it()'")
        return datetime.now(UTC)

    @server.handle_hold_temperature
    def hold_temperature(temperature_celsius: float) -> bool:
        """This is an example handler for the 'hold_temperature' method."""
        print(f"--> Running hold_temperature({temperature_celsius})'")
        return True

    print("Ctrl-C will stop the program.")

    while True:
        try:
            server.emit_today_is(42, DayOfTheWeek.SATURDAY)
            server.emit_random_word("apples", datetime.now(UTC))

            sleep(4)
            server.emit_today_is(day_of_month=42, day_of_week=DayOfTheWeek.SATURDAY)
            server.emit_random_word(word="apples", time=datetime.now(UTC))

            sleep(42)
        except KeyboardInterrupt:
            break

    signal.pause()
