"""
DO NOT MODIFY THIS FILE.  It is automatically generated by Stinger-IPC 0.7.0 and changes will be over-written
on the next generation.

LICENSE: This generated code is not subject to any license restrictions from the generator itself.
TODO: Get license text from stinger file
"""

from typing import Callable, Optional

from pydantic import BaseModel
from .interface_types import *
