"""
DO NOT MODIFY THIS FILE.  It is automatically generated by Stinger-IPC 0.6.21 and changes will be over-written
on the next generation.

LICENSE: This generated code is not subject to any license restrictions from the generator itself.
TODO: Get license text from stinger file
"""

from typing import Callable, Optional

from pydantic import BaseModel
from .interface_types import *


class TestableInitialPropertyValues(BaseModel):
    """This class holds all the initial property values for the testable interface.
    Since the application owns property values, this is only used for testing.
    """

    read_write_integer: int
    read_write_integer_version: int = 0

    read_only_integer: int
    read_only_integer_version: int = 0

    read_write_optional_integer: Optional[int]
    read_write_optional_integer_version: int = 0

    read_write_two_integers: ReadWriteTwoIntegersProperty
    read_write_two_integers_version: int = 0

    read_only_string: str
    read_only_string_version: int = 0

    read_write_string: str
    read_write_string_version: int = 0

    read_write_optional_string: Optional[str]
    read_write_optional_string_version: int = 0

    read_write_two_strings: ReadWriteTwoStringsProperty
    read_write_two_strings_version: int = 0

    read_write_struct: AllTypes
    read_write_struct_version: int = 0

    read_write_optional_struct: Optional[AllTypes]
    read_write_optional_struct_version: int = 0

    read_write_two_structs: ReadWriteTwoStructsProperty
    read_write_two_structs_version: int = 0

    read_only_enum: Numbers
    read_only_enum_version: int = 0

    read_write_enum: Numbers
    read_write_enum_version: int = 0

    read_write_optional_enum: Optional[Numbers]
    read_write_optional_enum_version: int = 0

    read_write_two_enums: ReadWriteTwoEnumsProperty
    read_write_two_enums_version: int = 0

    read_write_datetime: datetime
    read_write_datetime_version: int = 0

    read_write_optional_datetime: Optional[datetime]
    read_write_optional_datetime_version: int = 0

    read_write_two_datetimes: ReadWriteTwoDatetimesProperty
    read_write_two_datetimes_version: int = 0

    read_write_duration: timedelta
    read_write_duration_version: int = 0

    read_write_optional_duration: Optional[timedelta]
    read_write_optional_duration_version: int = 0

    read_write_two_durations: ReadWriteTwoDurationsProperty
    read_write_two_durations_version: int = 0

    read_write_binary: bytes
    read_write_binary_version: int = 0

    read_write_optional_binary: Optional[bytes]
    read_write_optional_binary_version: int = 0

    read_write_two_binaries: ReadWriteTwoBinariesProperty
    read_write_two_binaries_version: int = 0

    read_write_list_of_strings: List[str]
    read_write_list_of_strings_version: int = 0

    read_write_lists: ReadWriteListsProperty
    read_write_lists_version: int = 0


class TestablePropertyAccess(BaseModel):
    """This class holds all the ways to get and set the properties for the testable interface."""

    read_write_integer_getter: Callable[[], int]
    read_write_integer_setter: Callable[[int], None]
    read_only_integer_getter: Callable[[], int]
    read_write_optional_integer_getter: Callable[[], Optional[int]]
    read_write_optional_integer_setter: Callable[[Optional[int]], None]
    read_write_two_integers_getter: Callable[[], ReadWriteTwoIntegersProperty]
    read_write_two_integers_setter: Callable[[ReadWriteTwoIntegersProperty], None]
    read_only_string_getter: Callable[[], str]
    read_write_string_getter: Callable[[], str]
    read_write_string_setter: Callable[[str], None]
    read_write_optional_string_getter: Callable[[], Optional[str]]
    read_write_optional_string_setter: Callable[[Optional[str]], None]
    read_write_two_strings_getter: Callable[[], ReadWriteTwoStringsProperty]
    read_write_two_strings_setter: Callable[[ReadWriteTwoStringsProperty], None]
    read_write_struct_getter: Callable[[], AllTypes]
    read_write_struct_setter: Callable[[AllTypes], None]
    read_write_optional_struct_getter: Callable[[], Optional[AllTypes]]
    read_write_optional_struct_setter: Callable[[Optional[AllTypes]], None]
    read_write_two_structs_getter: Callable[[], ReadWriteTwoStructsProperty]
    read_write_two_structs_setter: Callable[[ReadWriteTwoStructsProperty], None]
    read_only_enum_getter: Callable[[], Numbers]
    read_write_enum_getter: Callable[[], Numbers]
    read_write_enum_setter: Callable[[Numbers], None]
    read_write_optional_enum_getter: Callable[[], Optional[Numbers]]
    read_write_optional_enum_setter: Callable[[Optional[Numbers]], None]
    read_write_two_enums_getter: Callable[[], ReadWriteTwoEnumsProperty]
    read_write_two_enums_setter: Callable[[ReadWriteTwoEnumsProperty], None]
    read_write_datetime_getter: Callable[[], datetime]
    read_write_datetime_setter: Callable[[datetime], None]
    read_write_optional_datetime_getter: Callable[[], Optional[datetime]]
    read_write_optional_datetime_setter: Callable[[Optional[datetime]], None]
    read_write_two_datetimes_getter: Callable[[], ReadWriteTwoDatetimesProperty]
    read_write_two_datetimes_setter: Callable[[ReadWriteTwoDatetimesProperty], None]
    read_write_duration_getter: Callable[[], timedelta]
    read_write_duration_setter: Callable[[timedelta], None]
    read_write_optional_duration_getter: Callable[[], Optional[timedelta]]
    read_write_optional_duration_setter: Callable[[Optional[timedelta]], None]
    read_write_two_durations_getter: Callable[[], ReadWriteTwoDurationsProperty]
    read_write_two_durations_setter: Callable[[ReadWriteTwoDurationsProperty], None]
    read_write_binary_getter: Callable[[], bytes]
    read_write_binary_setter: Callable[[bytes], None]
    read_write_optional_binary_getter: Callable[[], Optional[bytes]]
    read_write_optional_binary_setter: Callable[[Optional[bytes]], None]
    read_write_two_binaries_getter: Callable[[], ReadWriteTwoBinariesProperty]
    read_write_two_binaries_setter: Callable[[ReadWriteTwoBinariesProperty], None]
    read_write_list_of_strings_getter: Callable[[], List[str]]
    read_write_list_of_strings_setter: Callable[[List[str]], None]
    read_write_lists_getter: Callable[[], ReadWriteListsProperty]
    read_write_lists_setter: Callable[[ReadWriteListsProperty], None]
