"""
Generated by Stinger-IPC code generator 0.6.21.
"""

from time import sleep
import signal
import os
from typing import Optional, Union, List
from datetime import datetime, timedelta, UTC
from pyqttier import Mqtt5Connection, MqttTransportType, MqttTransport
from signalonlyipc.server import SignalOnlyServer
from signalonlyipc.interface_types import *

if __name__ == "__main__":
    """
    This shows an example on how to run the code.  Ideally, your app should do something similar, but use the methods in
    a more meaningful way.
    """

    transport = MqttTransport(MqttTransportType.TCP, "localhost", 1883)
    conn = Mqtt5Connection(transport, client_id=os.environ.get("CLIENT_ID", "py-server-demo"))
    server = SignalOnlyServer(conn, os.environ.get("SERVICE_ID", "py-server-demo:1"))

    print("Ctrl-C will stop the program.")

    while True:
        try:
            server.emit_another_signal(3.14, True, "apples")
            server.emit_bark("apples")
            server.emit_maybe_number(42)
            server.emit_maybe_name("apples")
            server.emit_now(datetime.now(UTC))

            sleep(4)
            server.emit_another_signal(one=3.14, two=True, three="apples")
            server.emit_bark(word="apples")
            server.emit_maybe_number(number=42)
            server.emit_maybe_name(name="apples")
            server.emit_now(timestamp=datetime.now(UTC))

            sleep(42)
        except KeyboardInterrupt:
            break

    signal.pause()
