"""
DO NOT MODIFY THIS FILE.  It is automatically generated by Stinger-IPC 0.6.12 and changes will be over-written
on the next generation.

LICENSE: This generated code is not subject to any license restrictions from the generator itself.
TODO: Get license text from stinger file
"""

from typing import Callable, Optional

from pydantic import BaseModel
from .interface_types import *


class SimpleInitialPropertyValues(BaseModel):
    """This class holds all the initial property values for the Simple interface.
    Since the application owns property values, this is only used for testing.
    """

    school: str
    school_version: int = 0


class SimplePropertyAccess(BaseModel):
    """This class holds all the ways to get and set the properties for the Simple interface."""

    school_getter: Callable[[], str]
    school_setter: Callable[[str], None]
