"""
Generated by Stinger-IPC code generator 0.6.14.
"""

from time import sleep
import signal
import os
from typing import Optional, Union, List
from datetime import datetime, timedelta, UTC
from pyqttier import Mqtt5Connection, MqttTransportType, MqttTransport
from simpleipc.server import SimpleServer
from simpleipc.property import SimplePropertyAccess
from simpleipc.interface_types import *


class SimplePropertyOwnership:
    def __init__(self):
        self._school = "apples"

    def get_property_school(self):
        """Return the value for the 'school' property."""
        return self._school

    def set_property_school(self, value: str):
        """Set the value for the 'school' property."""
        print(f"~~> Received update for 'school' property: {value}")
        self._school = value


if __name__ == "__main__":
    """
    This shows an example on how to run the code.  Ideally, your app should do something similar, but use the methods in
    a more meaningful way.
    """

    property_owner = SimplePropertyOwnership()
    property_access = SimplePropertyAccess(
        school_getter=property_owner.get_property_school,
        school_setter=property_owner.set_property_school,
    )

    transport = MqttTransport(MqttTransportType.TCP, "localhost", 1883)
    conn = Mqtt5Connection(transport, client_id=os.environ.get("CLIENT_ID", "py-server-demo"))
    server = SimpleServer(conn, os.environ.get("SERVICE_ID", "py-server-demo:1"), property_access)

    @server.handle_trade_numbers
    def trade_numbers(your_number: int) -> int:
        """This is an example handler for the 'trade_numbers' method."""
        print(f"--> Running trade_numbers({your_number})'")
        return 42

    print("Ctrl-C will stop the program.")

    while True:
        try:
            server.emit_person_entered(Person(name="apples", gender=Gender.MALE))

            sleep(4)
            server.emit_person_entered(person=Person(name="apples", gender=Gender.MALE))

            sleep(42)
        except KeyboardInterrupt:
            break

    signal.pause()
