$id: "https://stingeripc.peargrove.com/stingeripc.schema.yaml"
$schema: "http://json-schema.org/draft-07/schema#"
description: |
  This schema is used to validate StingerIPC stinger files.
type: object

parameters:

  stingeripc:
    type: object
    properties:
      version:
        type: string
        const: "0.0.6"
    required:
      - version

  interface:
    type: object
    parameters:
      name:
        type: string
        pattern: "[a-zA-Z0-9_]+"
        maxLength: 32
        description: "A short token that will be used to create class names, folder names, filenames, etc."
      title:
        type: string
        maxLength: 64
        description: "A few words that are the title for the API.  Used at the top of documentation, etc.  The interface name is used if not provided."
      summary:
        type: string
        description: "A one sentence description of the service."
        maxLength: 128
      version:
        type: string
        maxLength: 32
    required:
      - name
      - version
  
  brokers:
    type: object
    additionalProperties:
      type: object
      properties:
        host:
          type: string
        port:
          type: integer
        protocol:
          type: string
          enum:
            - tcp
            - websockets
          default: tcp
        secure:
          type: boolean
          default: false
        description:
          type: string

      dependentRequired:
        host: ["port"]

  enums:
    type: object
    additionalProperties:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
        required: [name]

  signals:
    type: object
    additionalProperties:
      $ref: "#/$defs/signal"

  params:
    type: object
    additionalProperties:
      $ref: "#/$defs/param"

  methods:
    type: object
    additionalProperties:
      $ref: "#/$defs/method"

required:
  - stingeripc
  - interface

$defs:

  payload:
    type: array
    uniqueItems: true
    items:
      type: object
      required:
        - "type"
        - "name"
      properties:
        name:
          type: string
        description:
          type: string
      oneOf:
        - properties:
            type:
              type: string
              const: "float"
            initialValue:
              type: float
        - properties:
            type:
              type: string
              const: "string"
            initialValue:
              type: string
        - properties:
            type:
              type: string
              const: "integer"
            initialValue:
              type: integer
        - properties:
            type:
              type: string
              const: "boolean"
            initialValue:
              type: boolean
        - properties:
            type: 
              type: string
              const: "enum"
            enumName:
              type: string
            initialValue:
              type: string
          required: ["enumName"]
            
  signal:
    type: object
    properties:
      payload:
        $ref: "#/$defs/payload"

  param:
    type: object
    properties:
      payload:
        allOf:
          - $ref: "#/$defs/payload"
          - items:
              required: ["initialValue"]
    required:
      - payload
  
  method:
    type: object
    properties:
      arguments:
        $ref: "#/$defs/payload"
      returnValues:
        $ref: "#/$defs/payload"
    required:
      - arguments