$id: "https://stingeripc.peargrove.com/stingeripc.schema.yaml"
$schema: "http://json-schema.org/draft-07/schema#"
description: |
  This schema is used to validate StingerIPC stinger files.
type: object

properties:

  stingeripc:
    type: object
    properties:
      version:
        type: string
        enum:
          - "0.0.7"
          - "0.0.8"
          - "0.0.9"
          - "0.1.0"
    required:
      - version

  interface:
    type: object
    parameters:
      name:
        type: string
        pattern: "^[a-zA-Z0-9_-]+$"
        maxLength: 32
        description: "A short token that will be used to create class names, folder names, filenames, etc."
      title:
        type: string
        maxLength: 64
        description: "A few words that are the title for the API.  Used at the top of documentation, etc.  The interface name is used if not provided."
      summary:
        type: string
        description: "A one sentence description of the service."
        maxLength: 128
      version:
        type: string
        maxLength: 32
      documentation:
        $ref: "#/$defs/documentation"
      description: false
      license:
        type: string
        description: "The license or copyright under which this interface is provided.  All generated code will be subject to this license."
    required:
      - name
      - version

  enums:
    type: object
    propertyNames:
      pattern: "^[a-zA-Z0-9_-]+$"
    additionalProperties:
      type: object
      properties:
        values:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              name:
                type: string
                pattern: "^[a-zA-Z0-9_-]+$"
              description:
                $ref: "#/$defs/enumValueDescription"
              documentation: false
              value:
                type: integer
            required:
              - name
          version:
            type: string
            pattern: "^[0-9]+(\\.[0-9]+){0,2}$"
            description: >
              A semantic version that can be used to determine data consistency in this specification.
        documentation:
          $ref: "#/$defs/documentation"
        description: false
      required:
        - values

  enumerations: false # Use 'enums' instead

  structures:
    type: object
    propertyNames:
      pattern: "^[a-zA-Z0-9_-]+$"
    additionalProperties:
      type: object
      properties:
        members:
          $ref: "#/$defs/payload"
        documentation:
          $ref: "#/$defs/documentation"
        description: false
        version:
            type: string
            pattern: "^[0-9]+(\\.[0-9]+){0,2}$"
            description: >
              A semantic version that can be used to determine data consistency in this specification.
      required:
        - members
      dependentSchemas:
        version:
          properties:
            members:
              $ref: "#/$defs/enumsAndStructArgsMustHaveVersion"

  structs: false # Use 'structures' instead

  signals:
    type: object
    propertyNames:
      pattern: "^[a-zA-Z0-9_-]+$"
    additionalProperties:
      $ref: "#/$defs/signal"

  sigs: false # Use 'signals' instead

  properties:
    type: object
    propertyNames:
      pattern: "^[a-zA-Z0-9_-]+$"
    additionalProperties:
      $ref: "#/$defs/property"

  props: false # Use 'properties' instead

  methods:
    type: object
    propertyNames:
      pattern: "^[a-zA-Z0-9_-]+$"
    additionalProperties:
      $ref: "#/$defs/method"

  constants:
    type: object
    propertyNames:
      pattern: "^[a-zA-Z0-9_-]+$"
    additionalProperties:
      type: object
      properties:
        type:
          type: string
          enum:
            - float
            - string
            - integer
            - boolean
        value:
          type: ["string", "number", "boolean"]
        description:
          $ref: "#/$defs/constantValueDescription"
        documentation: false
      required:
        - type
        - value

  const: false # Use 'constants' instead

required:
  - stingeripc
  - interface

$defs:

  documentation:
    type: string
    description: "Documentation.  May be multi-line.  May be markdown formatted."

  argDescription:
    type: string
    description: "A short description of an argument as a single line."
    maxLength: 256
    pattern: "^[^\n\r]*$"
  payload:
    type: array
    uniqueItems: true
    items:
      $ref: "#/$defs/arg"

  enumValueDescription:
    type: string
    description: "A short description of an enum value as a single line."
    maxLength: 256
    pattern: "^[^\n\r]*$"

  constantValueDescription:
    type: string
    description: "A short description of a constant value as a single line."
    maxLength: 256
    pattern: "^[^\n\r]*$"

  genericArg:
    type: object
    required:
      - "type"
      - "name"
    properties:
      name:
        type: string
        pattern: "^[a-zA-Z0-9_-]+$"
      optional:
        type: boolean
        default: false
      description:
        $ref: "#/$defs/argDescription"
      documentation: false
      schema:
        type: object
        description: A JSON schema which further constrains the value.
      index:
        type: integer
        minimum: 1
        description: >
          Payload ordering index required for some serialization formats.
      example:
        description: An example value used in demo code and documentation.

  primitiveArg:
    properties:
      type:
        type: string
        enum:
          - float
          - string
          - integer
          - boolean
          - datetime
          - duration
          - binary
      example:
        description: An example value used in demo code and documentation.
        type: ["string", "number", "boolean", "integer", "null"]

  enumArg:
    properties:
      type:
        type: string
        const: "enum"
      enumName:
        type: string
      enumVersion:
        type: string
        pattern: "^[0-9]+(\\.[0-9]+){0,2}$"
        description: >
          This must be semantically compatible with the version defined in the enums section.
      example:
        description: An example value used in demo code and documentation.
        type: ["string", "null"]
    required:
      - enumName

  structArg:
    properties:
      type:
        type: string
        const: "struct"
      structName:
        type: string
      structVersion:
        type: string
        pattern: "^[0-9]+(\\.[0-9]+){0,2}$"
        description: >
          This must be semantically compatible with the version defined in the structures section.
      example:
        description: An example value used in demo code and documentation.
        type: ["object", "null"]
    required:
      - structName

  arrayArg:
    properties:
      type:
        type: string
        const: "array"
      itemType:
        oneOf:
          - $ref: "#/$defs/primitiveArg"
          - $ref: "#/$defs/enumArg"
          - $ref: "#/$defs/structArg"
      example:
        description: An example value used in demo code and documentation.
        type: ["array", "null"]
    required:
      - itemType

  arg:
    oneOf:
      - allOf:
        - $ref: "#/$defs/genericArg"
        - $ref: "#/$defs/primitiveArg"
      - allOf:
        - $ref: "#/$defs/genericArg"
        - $ref: "#/$defs/enumArg"
      - allOf:
        - $ref: "#/$defs/genericArg"
        - $ref: "#/$defs/structArg"
      - allOf:
        - $ref: "#/$defs/genericArg"
        - $ref: "#/$defs/arrayArg"

  enumsAndStructArgsMustHaveVersion:
    type: array
    items:
      allOf:
        - type: object
          if:
            properties:
              type:
                const: enum
          then:
            properties:
              enumVersion: true
        - type: object
          if:
            properties:
              type:
                const: struct
          then:
            properties:
              structVersion: true

  signal:
    type: object
    properties:
      documentation:
        $ref: "#/$defs/documentation"
      description: false
      payload:
        $ref: "#/$defs/payload"
      consumers:
        type: array
        items:
          type: string
          pattern: "^[a-zA-Z0-9_-]+$"
        uniqueItems: true
        description: >
          A list of names representing interface consumers that are allowed receive this signal.
      version:
        type: string
        pattern: "^[0-9]+(\\.[0-9]+){0,2}$"
        description: >
          A semantic version that can be used by consumers to check compatibility.
    dependentRequired:
      consumers:
        - version
    dependentSchemas:
      payload:
        properties:
          arguments:
            $ref: "#/$defs/enumsAndStructArgsMustHaveVersion"

  property:
    type: object
    properties:
      documentation:
        $ref: "#/$defs/documentation"
      description: false
      values:
        type: array
        uniqueItems: true
        items:
          $ref: "#/$defs/arg"
        minItems: 1
      readOnly:
        type: boolean
        default: false
        description: >
          If true, this property can only be read by clients, not written to.
      consumers:
        type: array
        items:
          type: string
          pattern: "^[a-zA-Z0-9_-]+$"
        uniqueItems: true
        description: >
          A list of names representing interface consumers that are allowed access to this property.
      version:
        type: string
        pattern: "^[0-9]+(\\.[0-9]+){0,2}$"
        description: >
          A semantic version that can be used by consumers to check compatibility.
    required:
      - values
    dependentRequired:
      consumers:
        - version
    dependentSchemas:
      version:
        properties:
          values:
            $ref: "#/$defs/enumsAndStructArgsMustHaveVersion"

  method:
    type: object
    properties:
      documentation:
        $ref: "#/$defs/documentation"
      description: false
      arguments:
        $ref: "#/$defs/payload"
      returnValues:
        $ref: "#/$defs/payload"
      consumers:
        type: array
        items:
          type: string
          pattern: "^[a-zA-Z0-9_-]+$"
        uniqueItems: true
        description: >
          A list of names representing interface consumers that are allowed to call this method.
      version:
        type: string
        pattern: "^[0-9]+(\\.[0-9]+){0,2}$"
        description: >
          A semantic version that can be used by consumers to check compatibility.
    required:
      - arguments
    dependentRequired:
      consumers:
        - version
    dependentSchemas:
      version:
        properties:
          arguments:
            $ref: "#/$defs/enumsAndStructArgsMustHaveVersion"
          returnValues:
            $ref: "#/$defs/enumsAndStructArgsMustHaveVersion"
