name: Mypy Check

# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the main/master branch.
on:
  push:
    branches: [ main, master ] # Adjust to your default branch if different
  pull_request:
    branches: [ main, master ] # Adjust to your default branch if different

jobs:
  mypy:
    runs-on: ubuntu-latest # You can choose other runners like macos-latest or windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install

    - name: Run Mypy
      run: |
        uvx mypy stingeripc/
