name: Mypy Check

# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the main/master branch.
on:
  push:
    branches: [ main, master ] # Adjust to your default branch if different
  pull_request:
    branches: [ main, master ] # Adjust to your default branch if different

jobs:
  mypy:
    runs-on: ubuntu-latest # You can choose other runners like macos-latest or windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # Specify Python versions to test against

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run Mypy
      run: |
        uvx mypy stingeripc/
